package net.tacobuddies.bot.api.constants

import net.runelite.api.widgets.WidgetInfo

enum class InterfaceTab(val fixed: WidgetInfo, val resizableClassic: WidgetInfo, val resizableModern: WidgetInfo) {
    CombatOptions(
        WidgetInfo.FIXED_VIEWPORT_COMBAT_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_COMBAT_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_COMBAT_ICON
    ),
    Skills(
        WidgetInfo.FIXED_VIEWPORT_STATS_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_STATS_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_STATS_ICON
    ),
    Quests(
        WidgetInfo.FIXED_VIEWPORT_QUESTS_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_QUESTS_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_QUESTS_ICON
    ),
    Inventory(
        WidgetInfo.FIXED_VIEWPORT_INVENTORY_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_INVENTORY_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_ICON
    ),
    Equipment(
        WidgetInfo.FIXED_VIEWPORT_EQUIPMENT_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_EQUIPMENT_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_EQUIPMENT_ICON
    ),
    Prayer(
        WidgetInfo.FIXED_VIEWPORT_PRAYER_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_PRAYER_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_PRAYER_ICON
    ),
    Magic(
        WidgetInfo.FIXED_VIEWPORT_MAGIC_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_MAGIC_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_MAGIC_ICON
    ),
    ChatChannels(
        WidgetInfo.FIXED_VIEWPORT_FRIENDS_CHAT_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_FRIENDS_CHAT_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_CHAT_ICON
    ),
    AccountManagement(
        WidgetInfo.FIXED_VIEWPORT_IGNORES_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_IGNORES_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_ICON
        //TODO: This API version of RuneLite (1.10.10) does not include the resizable modern widget we need
    ),
    FriendsLists(
        WidgetInfo.FIXED_VIEWPORT_FRIENDS_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_FRIENDS_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_ICON
    ),
    Logout(
        WidgetInfo.FIXED_VIEWPORT_LOGOUT_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_LOGOUT_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_LOGOUT_BUTTON
    ),
    Settings(
        WidgetInfo.FIXED_VIEWPORT_OPTIONS_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_OPTIONS_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_OPTIONS_ICON
    ),
    Emotes(
        WidgetInfo.FIXED_VIEWPORT_EMOTES_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_EMOTES_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_EMOTES_ICON
    ),
    MusicPlayer(
        WidgetInfo.FIXED_VIEWPORT_MUSIC_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_MUSIC_ICON,
        WidgetInfo.RESIZABLE_VIEWPORT_BOTTOM_LINE_MUSIC_ICON
    ),
    NotSelected(
        WidgetInfo.CHATBOX_FULL_INPUT,
        WidgetInfo.CHATBOX_FULL_INPUT,
        WidgetInfo.CHATBOX_FULL_INPUT
    )
}